# Generated by Django 4.1.5 on 2023-02-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_tag_projects_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(max_length=800),
        ),
    ]
