# Generated by Django 4.1.5 on 2023-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_projects_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="price",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
